using System;
using System.Collections.Generic;

namespace LogicSim
{
    /// <summary>
    /// A wrapper for the file data generated by FileReader and used by Computer
    /// </summary>
    public class FileData
    {
        public readonly Dictionary<Variable, ICommand> localVariables;
        public readonly List<Variable> inputVariables;

        public FileData(Dictionary<Variable, ICommand> localVariables, List<Variable> inputVariables)
        {
            this.localVariables = localVariables;
            this.inputVariables = inputVariables;
        }
    }
}
