using System;
using System.Collections.Generic;
using System.Linq;
using LogicSim.Commands;

namespace LogicSim
{
    /// <summary>
    /// A wrapper for the file data generated by FileReader and used by Computer
    /// </summary>
    public class FileData
    {
        public readonly Dictionary<Variable, Command> localVariables;
        public readonly List<Variable> inputVariables;

        public FileData(Dictionary<Variable, Command> localVariables, List<Variable> inputVariables)
        {
            this.localVariables = localVariables;
            this.inputVariables = inputVariables;
        }

        /// <summary>
        /// Get all the variables in a list, both input and local
        /// </summary>
        /// <returns></returns>
        public List<Variable> GetAllVariables()
        {
            return localVariables.Keys.Concat(inputVariables).ToList();
        }
    }
}
